### ISSUE TITLE
Error during installation:  react-native-opentok:_debugCompile'.

### ISSUE THREAD

**Issue by LucasSouzaa** [callstack-io/react-native-opentok#13]
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-opentok'.
   > Could not resolve all dependencies for configuration ':react-native-opentok:_debugCompile'.
      > Could not find any matches for com.opentok.android:opentok-android-sdk:2.8.+ as no versions of com.opentok.android:opentok-android-sdk are available.

**Comment by LucasSouzaa** [comment]
Sorry for open this issue...
Fixed adding the repositorie on android\build.gradle
maven {
            url  "http://tokbox.bintray.com/maven"
        }

**Comment by radko93** [comment]
It would be great if you could make a PR with this change!
